apiVersion: v1
kind: Namespace
metadata:
  name: pms
  labels:
    name: pms
    project: mental-health-pms
    compliance: hipaa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pms-backend
  namespace: pms
  labels:
    app: pms-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pms-frontend
  namespace: pms
  labels:
    app: pms-frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pms
  name: pms-backend-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pms-backend-rolebinding
  namespace: pms
subjects:
- kind: ServiceAccount
  name: pms-backend
  namespace: pms
roleRef:
  kind: Role
  name: pms-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pms
  name: pms-frontend-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pms-frontend-rolebinding
  namespace: pms
subjects:
- kind: ServiceAccount
  name: pms-frontend
  namespace: pms
roleRef:
  kind: Role
  name: pms-frontend-role
  apiGroup: rbac.authorization.k8s.io
