# Dependabot configuration for automated dependency updates
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (Backend)
  - package-ecosystem: "pip"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "backend-team"
      - "security-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps(backend)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
    groups:
      testing:
        patterns:
          - "pytest*"
          - "factory-boy"
          - "httpx"
      linting:
        patterns:
          - "black"
          - "flake8*"
          - "isort"
          - "mypy"
      security:
        patterns:
          - "cryptography"
          - "python-jose*"
          - "passlib*"

  # Node.js dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "frontend-team"
      - "security-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps(frontend)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for React ecosystem
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react*"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      testing:
        patterns:
          - "@testing-library/*"
          - "@vitest/*"
          - "vitest"
          - "jsdom"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"

  # Infrastructure dependencies
  - package-ecosystem: "pip"
    directory: "/apps/infra"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "devops-team"
      - "platform-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps(infra)"
      include: "scope"
    labels:
      - "dependencies"
      - "infrastructure"
      - "automated"
    groups:
      aws:
        patterns:
          - "boto*"
      kubernetes:
        patterns:
          - "kubernetes"
      monitoring:
        patterns:
          - "prometheus*"
      security:
        patterns:
          - "bandit"
          - "safety"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "devops-team"
      - "security-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  - package-ecosystem: "docker"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "devops-team"
      - "security-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "devops-team"
    assignees:
      - "tech-lead"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"
