# Pre-commit hooks for automated code quality checks
# See https://pre-commit.com for more information

repos:
  # Python code quality
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^apps/backend/
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^apps/backend/
        args: [--profile=black, --line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^apps/backend/
        args: [--max-line-length=88, --extend-ignore=E203]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^apps/backend/
        additional_dependencies: [types-requests, types-setuptools]
        args: [--ignore-missing-imports, --strict-optional]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^apps/backend/
        args: [-r, -f, json, -o, bandit-report.json]
        exclude: ^apps/backend/tests/

  # - repo: https://github.com/gitguardian/ggshield
  #   rev: v1.25.0
  #   hooks:
  #     - id: ggshield
  #       language: python
  #       stages: [pre-commit]

  # Conventional commits validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, --optional-scope]

  # Commit message linting
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.8.0
    hooks:
      - id: commitlint
        stages: [commit-msg]

  # Frontend code quality
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.35.0
    hooks:
      - id: eslint
        files: ^apps/frontend/src/.*\.(ts|tsx)$
        args: [--fix, --max-warnings=0]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: ^apps/frontend/src/.*\.(ts|tsx|css|md)$
        args: [--write]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.(md|rst)$
      - id: end-of-file-fixer
        exclude: ^.*\.(md|rst)$
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^apps/infra/kubernetes/helm/.*\.yaml$
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

  # Docker (disabled - permission issues)
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.12.0
  #   hooks:
  #     - id: hadolint-docker
  #       args: [--ignore, DL3008, --ignore, DL3009]

  # Infrastructure as Code (disabled - terraform not installed)
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.83.6
  #   hooks:
  #     - id: terraform_fmt
  #       files: ^apps/infra/terraform/
  #     - id: terraform_validate
  #       files: ^apps/infra/terraform/
  #     - id: terraform_docs
  #       files: ^apps/infra/terraform/

  # Commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Documentation
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
        files: ^apps/backend/
      - id: python-check-blanket-type-ignore
        files: ^apps/backend/
      - id: python-no-log-warn
        files: ^apps/backend/
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

# Configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: '3.0.0'

# Exclude patterns
exclude: |
  (?x)^(
    .*/migrations/.*|
    .*/node_modules/.*|
    .*/\.venv/.*|
    .*/\.mypy_cache/.*|
    .*/\.pytest_cache/.*|
    .*/__pycache__/.*|
    .*/dist/.*|
    .*/build/.*|
    .*/coverage/.*|
    .*/htmlcov/.*|
    keys\.txt|
    test_event_system\.py|
    apps/backend/docs/updated_erd_visual\.svg|
    apps/backend/flake8-report\.json
  )$
