"""Add foreign key constraint from auth_tokens to users

Revision ID: d40ecb01ecd0
Revises: c760c2bd93c2
Create Date: 2025-08-04 14:22:19.165784

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d40ecb01ecd0"
down_revision = "c760c2bd93c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "auth_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # Cannot index JSON column - commented out
    # op.create_index('idx_users_active_roles', 'users',
    #                 ['is_active', 'roles'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Cannot index JSON column - commented out
    # op.drop_index('idx_users_active_roles', table_name='users')
    op.drop_constraint("auth_tokens_user_id_fkey", "auth_tokens", type_="foreignkey")
    # ### end Alembic commands ###
