"""Sync database schema with models

Revision ID: a4226ccee6fc
Revises: 0001
Create Date: 2025-08-02 14:20:53.774404

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a4226ccee6fc"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_appointments_client_id"), "appointments", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_correlation_id"),
        "appointments",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appointments_provider_id"),
        "appointments",
        ["provider_id"],
        unique=False,
    )
    op.alter_column(
        "audit_log",
        "correlation_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "audit_log",
        "old_values",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_log",
        "new_values",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_log",
        "ip_address",
        existing_type=postgresql.INET(),
        type_=sa.String(length=45),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_audit_log_correlation_id"),
        "audit_log",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_clients_correlation_id"), "clients", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=False)
    op.create_index(op.f("ix_ledger_client_id"), "ledger", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_ledger_correlation_id"), "ledger", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_notes_appointment_id"), "notes", ["appointment_id"], unique=False
    )
    op.create_index(op.f("ix_notes_client_id"), "notes", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_notes_correlation_id"), "notes", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_notes_provider_id"), "notes", ["provider_id"], unique=False
    )
    op.drop_constraint("providers_email_key", "providers", type_="unique")
    op.create_index(
        op.f("ix_providers_correlation_id"),
        "providers",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_providers_email"), "providers", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_providers_email"), table_name="providers")
    op.drop_index(op.f("ix_providers_correlation_id"), table_name="providers")
    op.create_unique_constraint(
        "providers_email_key",
        "providers",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_notes_provider_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_correlation_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_client_id"), table_name="notes")
    op.drop_index(op.f("ix_notes_appointment_id"), table_name="notes")
    op.drop_index(op.f("ix_ledger_correlation_id"), table_name="ledger")
    op.drop_index(op.f("ix_ledger_client_id"), table_name="ledger")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_index(op.f("ix_clients_correlation_id"), table_name="clients")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_correlation_id"), table_name="audit_log")
    op.alter_column(
        "audit_log",
        "ip_address",
        existing_type=sa.String(length=45),
        type_=postgresql.INET(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_log",
        "new_values",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_log",
        "old_values",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_log",
        "correlation_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_index(op.f("ix_appointments_provider_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_correlation_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_client_id"), table_name="appointments")
    # ### end Alembic commands ###
